export const GET_SUBJECT_LIST = 'GET_SUBJECT_LIST'
export const GET_SEC_SUBJECT_LIST = 'GET_SEC_SUBJECT_LIST'
export const UPDATE_SUBJECT_LIST = 'UPDATE_SUBJECT_LIST'
export const DEL_SUBJECT_LIST = 'DEL_SUBJECT_LIST'